jenkins:
  systemMessage: "Sample CI Server"
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  nodejs:
    installations:
      - name: "NodeJS"
        home: ""
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "10.18.1"
                    npmPackagesRefreshHours: 48
unclassified:
  globalLibraries:
    libraries:
      - name: "my-pipeline-library"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/tadeumendonca/jenkins-casc.git"
jobs:
    - script: >
        multibranchPipelineJob('Sample Application') {
            branchSources {
                git {
                    id('1')
                    remote('https://github.com/tadeumendonca/node-sample-app-with-test.git')
                }
            }
            orphanedItemStrategy {
                discardOldItems {
                    numToKeep(20)
                }
            }
        }