version: '3.3'
services:
  jenkins:
    build: ./jenkins
    restart: unless-stopped
    environment: 
      - JENKINS_USER=admin
      - JENKINS_PASS=abc1234#
    user: root # Required only for localhost on MAC due to docker.sock mapping.
    ports:
      - 8080:8080
    networks:
      - devops
    volumes:
      - ./volumes/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
networks:
  devops:
    driver: bridge